In [28]:
from __future__ import print_function

import tensorflow as tf
try:
    tf.contrib.eager.enable_eager_execution()
    print("TF imported")
except ValueError:
    print("TF already imported!")
    
# List of primes
primes = tf.constant([2,3,5,7,11,13, 17], dtype=tf.int32)
print("primes:", primes)

# Creates a list of seven ones
ones = tf.ones([7], dtype=tf.int32)
print("ones:", ones)

just_beyond_primes = tf.add(primes, ones)
print("just_beyond_primes:", just_beyond_primes)

twos = tf.constant([2,2,2,2,2,2,2], dtype=tf.int32)
primes_doubled = primes * twos
print("primes_doubled", primes_doubled)

some_matrix = tf.constant([[1,2,3], [4,5,6]], dtype=tf.int32)
print(some_matrix)
print("\nvalue of some_matrix is:\n", some_matrix.numpy())

# A scalar
scalar = tf.zeros([])

# Vector with 3 elements
vector = tf.zeros([3])

# A matrix with 2 rows and 3 columns
matrix = tf.zeros([2,3])
bigger_matrix = tf.zeros([6,6])

print('scalar has shape', scalar.get_shape(), 'and value:\n', scalar.numpy())
print('vector has shape', vector.get_shape(), 'and value:\n', vector.numpy())
print('matrix has shape', matrix.get_shape(), 'and value:\n', matrix.numpy())
print('bigger matrix has shape', bigger_matrix.get_shape(), 'and value:\n', bigger_matrix.numpy())

###
# Broadcasting
# Tensors don't have to be the same size...

one = tf.constant(1, dtype=tf.int32)
print("one:", one)

just_beyond_primes = tf.add(primes, one)
print("just_beyond_primes:", just_beyond_primes)
print("\n")


###
# Exercise 1
primes_squared = tf.pow(primes, 2)
just_under_primes_squared = tf.subtract(primes_squared, one)
print("primes:", primes)
print("just_under_primes:", just_under_primes_squared)


###
# Matrix multiplication

#4x4 matrix
x = tf.constant([[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]], dtype=tf.int32)
#4x2 matrix
y = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6],
                 [7, 8]], dtype=tf.int32)

matrix_result = tf.matmul(x,y)

print(matrix_result)
print("\n", matrix_result.numpy())


###
#Tensor Reshaping
# tf.reshape method reshapes a tensor so you can change a 8x2 into a 2x8 or 4x4

matrix = tf.constant([[1,2], [2,3], [3,4], [4,5], [5,6], [6,7], [7,8], [8,9]], dtype=tf.int32)

reshaped_2x8 = tf.reshape(matrix, [2,8])
reshaped_4x4 = tf.reshape(matrix, [4,4])

print("Original matrix (8x2)")
print(matrix.numpy())
print("Reshaped matrix (2x8)")
print(reshaped_2x8.numpy())
print("Reshaped matrix (4x4)")
print(reshaped_4x4.numpy())

reshaped_2x2x4 = tf.reshape(matrix, [2,2,4])
one_dimensional_vector = tf.reshape(matrix, [16])

print("Reshaped 3-D tensor (2x2x4)")
print(reshaped_2x2x4.numpy())
print("1-D vector:")
print(one_dimensional_vector.numpy())



###
# Exercise 2
###

a = tf.constant([5,3,2,7,1,4])
b = tf.constant([4,6,3])

print("Origianl matrix (a):")
print(a.numpy())
print("Original matrix (b):")
print(b.numpy())

# Reshaping vectors to be able to multiply the vectors together
reshaped_a = tf.reshape(a, [2,3])
reshaped_b = tf.reshape(b, [3,1])

print("Reshaped matrix (a):")
print(reshaped_a.numpy())
print("Reshaped matrix (b):")
print(reshaped_b.numpy())

result = tf.matmul(reshaped_a,reshaped_b)

print("Matrix multiplication of axb", result.numpy())
print()

###
#Variables, Initialization, and Assignment
###

# Scalar with initial value 3
v = tf.contrib.eager.Variable([3])

# Vector shape [1,4] random initial values
w = tf.contrib.eager.Variable(tf.random_normal([1,4], mean=1.0, stddev=0.35))

print("v:", v.numpy())
print("w:", w.numpy())

# Changes value of the variable
tf.assign(v, [7])
print(v.numpy())

# Shape must be equal to previous shape!
r = tf.contrib.eager.Variable([[1,2,3], [4,5,6]])
print(v.numpy())

try:
    print("Assigning [7,8,9] to v")
    v.assign([7,8,9])
except ValueError as e:
    print("Exception", e)
    
    
###
#Exercise 3
###

first_die = tf.contrib.eager.Variable(tf.random_uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
second_die = tf.contrib.eager.Variable(tf.random_uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))

dice_sum = tf.add(first_die, second_die)

result = tf.concat([first_die, second_die, dice_sum], axis=1)

print(result.numpy())

TF already imported!
primes: tf.Tensor([ 2  3  5  7 11 13 17], shape=(7,), dtype=int32)
ones: tf.Tensor([1 1 1 1 1 1 1], shape=(7,), dtype=int32)
just_beyond_primes: tf.Tensor([ 3  4  6  8 12 14 18], shape=(7,), dtype=int32)
primes_doubled tf.Tensor([ 4  6 10 14 22 26 34], shape=(7,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

value of some_matrix is:
 [[1 2 3]
 [4 5 6]]
scalar has shape () and value:
 0.0
vector has shape (3,) and value:
 [0. 0. 0.]
matrix has shape (2, 3) and value:
 [[0. 0. 0.]
 [0. 0. 0.]]
bigger matrix has shape (6, 6) and value:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
one: tf.Tensor(1, shape=(), dtype=int32)
just_beyond_primes: tf.Tensor([ 3  4  6  8 12 14 18], shape=(7,), dtype=int32)


primes: tf.Tensor([ 2  3  5  7 11 13 17], shape=(7,), dtype=int32)
just_under_primes: tf.Tensor([  3   8  24  48 120 168 288], shape=(7,), dtype=int32)
tf.Tensor(
